### ISSUE TITLE
Connection refused when trying to start a LAN game

### ISSUE THREAD

**Issue by ChrisS85** [mmtrt/cncra2yr-snap#42]
The client crashes when trying to create a LAN game.
I'm running on a fresh Xubuntu installation, no custom settings regarding firewalls or similar.
Is this a snap issue?

cncra2yr has the :network and :network-bind interfaces, none of the others starting with :network

Here's the log output:

> snap run cncra2yr
> Starting application..
> Running hook '/snap/cncra2yr/93/sommelier/hooks/pre-start'
> 
> Unhandled Exception: System.Net.Sockets.SocketException: Verbindung abgelehnt 127.0.0.1:1233
>    at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
>    at DTAClient.DXGUI.Multiplayer.GameLobby.LANGameLobby.SetUp(Boolean isHost, IPEndPoint hostEndPoint, TcpClient client)
>    at DTAClient.DXGUI.Multiplayer.LANLobby.GameCreationWindow_NewGame(Object sender, EventArgs e)
>    at DTAClient.DXGUI.Multiplayer.LANGameCreationWindow.BtnNewGame_LeftClick(Object sender, EventArgs e)
>    at Rampastring.XNAUI.XNAControls.XNAControl.OnLeftClick()
>    at Rampastring.XNAUI.XNAControls.XNAButton.OnLeftClick()
>    at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAButton.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
>    at ClientGUI.DarkeningPanel.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
>    at DTAClient.DXGUI.Multiplayer.LANLobby.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
>    at Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
>    at ClientGUI.DarkeningPanel.Update(GameTime gameTime)
>    at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
>    at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
>    at Microsoft.Xna.Framework.Game.Tick()
>    at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
>    at Microsoft.Xna.Framework.GameHost.OnIdle()
>    at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
>    at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
>    at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
>    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.Run(Form mainForm)
>    at Microsoft.Xna.Framework.WindowsGameHost.Run()
>    at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
>    at DTAClient.Startup.Execute()
>    at DTAClient.PreStartup.Initialize(StartupParams parameters)
>    at DTAClient.Program.Main(String[] args)
> wine: Unhandled exception 0xe0434352 in thread 114 at address 7B0101D6 (thread 0114), starting debugger...
> Can't attach process 0110: error 5

**Comment by mmtrt** [comment]
pushed snap update it should be working now.
